mapping *who=({
(["name":"铁木真","id":"tie muzhen"]),
(["name":"巡逻亲兵","id":"qin bing"]),
(["name":"博尔术","id":"boer shu"]),
(["name":"近卫兵","id":"jinwei bing"]),
(["name":"察合台","id":"cha hetai"]),
(["name":"术赤","id":"shu chi"]),
(["name":"蒙古小孩","id":"kid"]),
(["name":"蒙古牧民","id":"mu min"]),
(["name":"哲别","id":"zhe bie"]),
(["name":"朱聪","id":"zhu cong"]),
(["name":"柯镇恶","id":"ke zhene"]),
(["name":"华筝公主","id":"hua zheng"]),
(["name":"郭靖","id":"guo jing"]),
(["name":"李萍","id":"li ping"]),
(["name":"城卫兵","id":"guard"]),
(["name":"钱老本","id":"qian laoben"]),
(["name":"剑客","id":"jian ke"]),
(["name":"刀客","id":"dao ke"]),
(["name":"武当派弃徒","id":"dizi"]),
(["name":"龙威风","id":"long weifeng"]),
(["name":"海大富","id":"hai dafu"]),
(["name":"小桂子","id":"xiao guizi"]),
(["name":"李力世","id":"li lishi"]),
(["name":"关安基","id":"guan anji"]),
(["name":"姚涤飞","id":"yao difei"]),
(["name":"龙虎道人","id":"dao ren"]),
(["name":"卫兵","id":"wei bing"]),
(["name":"孙太白","id":"sun taibai"]),
(["name":"小姐","id":"xiaojie"]),
(["name":"高渐离","id":"gao jianli"]),
(["name":"穆念慈","id":"mu nianci"]),
(["name":"杨铁心","id":"yang tiexin"]),
(["name":"公子","id":"gongzi"]),
(["name":"赵三钱","id":"zhao sanqian"]),
(["name":"张铁匠","id":"zhang tiejiang"]),
(["name":"王府亲兵","id":"qin bing"]),
(["name":"完颜康","id":"wanyan kang"]),
(["name":"沙通天","id":"sha tongtian"]),
(["name":"婢女","id":"bi nu"]),
(["name":"灵智上人","id":"lingzhi shangren"]),
(["name":"完颜洪烈","id":"wangye"]),
(["name":"仆人","id":"puren"]),
(["name":"王府看守","id":"kan shou"]),
(["name":"梁子翁","id":"liang ziweng"]),
(["name":"侯通海","id":"hou tonghai"]),
(["name":"梅超风","id":"mei chaofeng"]),
(["name":"包惜弱","id":"bao xiruo"]),
(["name":"绿林好汉","id":"haohan"]),
(["name":"瞎子","id":"xia zi"]),
(["name":"京千灵","id":"jing qianling"]),
(["name":"游方和尚","id":"seng ren"]),
(["name":"骁骑营军士","id":"junshi"]),
(["name":"察尔珠","id":"chaer zhu"]),
(["name":"游客","id":"youke"]),
(["name":"江湖豪客","id":"jianghu haoke"]),
(["name":"多隆","id":"duo long"]),
(["name":"皇宫侍卫","id":"shi wei"]),
(["name":"御前侍卫","id":"shi wei"]),
(["name":"索额图","id":"suo etu"]),
(["name":"明珠","id":"mingzhu"]),
(["name":"华伯斯基","id":"huabo siji"]),
(["name":"齐洛诺夫","id":"qiluo nuofu"]),
(["name":"张康年","id":"zhang kangnian"]),
(["name":"赵齐贤","id":"zhao qixian"]),
(["name":"瑞栋","id":"rui dong"]),
(["name":"小太监","id":"xiao taijian"]),
(["name":"胖大武士","id":"wushi"]),
(["name":"温有方","id":"wen youfang"]),
(["name":"温有道","id":"wen youdao"]),
(["name":"蕊初","id":"rui chu"]),
(["name":"皇太后","id":"huang taihou"]),
(["name":"柳无生","id":"liu wusheng"]),
(["name":"老郎中","id":"lao langzhong"]),
(["name":"老家人","id":"lao jiaren"]),
(["name":"叶浓衣","id":"ye nongyi"]),
(["name":"徐天川","id":"xu tianchuan"]),
(["name":"王府家丁","id":"jia ding"]),
(["name":"王府丫鬟","id":"ya huan"]),
(["name":"王府马夫","id":"ma fu"]),
(["name":"齐元凯","id":"qi yuankai"]),
(["name":"神照上人","id":"shang ren"]),
(["name":"康亲王","id":"kang qingwang"]),
(["name":"石牢看守","id":"kan shou"]),
(["name":"烧饭老汉","id":"lao han"]),
(["name":"鳌拜","id":"ao bai"]),
(["name":"苏佛儿","id":"su foer"]),
(["name":"玄真道长","id":"xuan zhen"]),
(["name":"吴六奇","id":"wu liuqi"]),
(["name":"陈近南","id":"chen jinnan"]),
(["name":"地痞","id":"di pi"]),
(["name":"卖唱女孩","id":"girl"]),
(["name":"窃贼","id":"qie zei"]),
(["name":"小丫鬟","id":"xiao yahuan"]),
(["name":"流氓","id":"liumang"]),
(["name":"老管家","id":"lao guanjia"]),
(["name":"白寒枫","id":"bai hanfeng"]),
(["name":"阿尔泰","id":"aer tai"]),
(["name":"前锋营军士","id":"junshi"]),
(["name":"玉林大师","id":"yu lin"]),
(["name":"贾老六","id":"jia laoliu"]),
(["name":"趟子手","id":"tangzi shou"]),
(["name":"书生","id":"shusheng"]),
(["name":"天乙道人","id":"tianyi daoren"]),
(["name":"挑夫","id":"tiao fu"]),
(["name":"天柏道人","id":"tianbai daoren"]),
(["name":"天松道人","id":"tiansong daoren"]),
(["name":"迟百城","id":"chi baicheng"]),
(["name":"泰山寻察使","id":"xuncha shi"]),
(["name":"建除道人","id":"jianchu daoren"]),
(["name":"玉磬子","id":"yuqing zi"]),
(["name":"天门道人","id":"tianmen daoren"]),
(["name":"小贩","id":"xiao fan"]),
(["name":"护掌使","id":"huzhang shi"]),
(["name":"白衣武士","id":"wei shi"]),
(["name":"玉音子","id":"yuyin zi"]),
(["name":"玉玑子","id":"yuji zi"]),
(["name":"无赖","id":"wulai"]),
(["name":"书场看客","id":"kanke"]),
(["name":"店小二","id":"xiaoer"]),
(["name":"韦小宝","id":"xiaobao"]),
(["name":"乞丐","id":"qigai"]),
(["name":"吃客","id":"chike"]),
(["name":"郎中","id":"langzhong"]),
(["name":"小孩子","id":"xiaohaizi"]),
(["name":"韦春花","id":"weichunhua"]),
(["name":"李逵","id":"likui"]),
(["name":"赌场小二","id":"xiaoer"]),
(["name":"齐天寿","id":"qi tianshou"]),
(["name":"姚德全","id":"yao dequan"]),
(["name":"兵勇","id":"bingyong"]),
(["name":"书童","id":"shutong"]),
(["name":"欧阳修","id":"ouyangxiu"]),
(["name":"唐伯虎","id":"tangbohu"]),
(["name":"秋香","id":"qiuxiang"]),
(["name":"门徒","id":"mentu"]),
(["name":"郑板桥","id":"zhengbanqiao"]),
(["name":"孙裁缝","id":"sun caifeng"]),
(["name":"王铁匠","id":"wang tiejiang"]),
(["name":"男孩","id":"nanhai"]),
(["name":"女孩","id":"nuhai"]),
(["name":"沈有财","id":"shen youcai"]),
(["name":"惠通","id":"zhuchi"]),
(["name":"知客僧","id":"zhike seng"]),
(["name":"船家","id":"chuanjia"]),
(["name":"船老大","id":"chuan laoda"]),
(["name":"奸商","id":"jian shang"]),
(["name":"邮差","id":"youchai"]),
(["name":"更夫","id":"geng fu"]),
(["name":"城卫","id":"chengwei"]),
(["name":"艳娘","id":"yan niang"]),
(["name":"高进昌","id":"gao jinchang"]),
(["name":"公子哥","id":"gongzi ge"]),
(["name":"赌场打手","id":"dashou"]),
(["name":"看场打手","id":"dashou"]),
(["name":"老鸨","id":"laobao"]),
(["name":"蓝精灵","id":"lan jingling"]),
(["name":"车夫","id":"chefu"]),
(["name":"孔老二","id":"kong laoer"]),
(["name":"欧阳克","id":"ouyang ke"]),
(["name":"都大锦","id":"du dajin"]),
(["name":"章巡捕","id":"zhang xunbu"]),
(["name":"陈帮办","id":"chen bangban"]),
(["name":"辛药农","id":"xin yaonong"]),
(["name":"巫攀冰","id":"wu panbing"]),
(["name":"戏院打手","id":"xiyuan dashou"]),
(["name":"男演员","id":"yanyuan"]),
(["name":"女演员","id":"yanyuan"]),
(["name":"观众","id":"guan zhong"]),
(["name":"武大郎","id":"wu dalang"]),
(["name":"中州地痞","id":"di pi"]),
(["name":"江上游","id":"jiang shangyou"]),
(["name":"老叫花","id":"lao jiaohua"]),
(["name":"小叫花","id":"xiao jiaohua"]),
(["name":"简长老","id":"jian zhanglao"]),
(["name":"黄飞鸿","id":"huang feihong"]),
(["name":"李老板","id":"li laoban"]),
(["name":"家丁","id":"jia ding"]),
(["name":"管家","id":"guan jia"]),
(["name":"雇工","id":"gu gong"]),
(["name":"老雇工","id":"lao gugong"]),
(["name":"茶老汉","id":"cha laohan"]),
(["name":"花剑影","id":"hua jianying"]),
(["name":"盖一鸣","id":"gai yiming"]),
(["name":"常长风","id":"chang changfeng"]),
(["name":"逍遥子","id":"xiaoyao zi"]),
(["name":"瞎眼老婆婆","id":"old woman"]),
(["name":"张山嫂","id":"sansao"]),
(["name":"张山","id":"zhang san"]),
(["name":"独臂神尼","id":"dubi shenni"]),
(["name":"周松天","id":"zhou songtian"]),
(["name":"姨太太","id":"yitai"]),
(["name":"富商","id":"fu shang"]),
(["name":"穷汉","id":"qong han"]),
(["name":"赵德言","id":"zhao deyan"]),
(["name":"仪文","id":"yi wen"]),
(["name":"仪质","id":"yi zhi"]),
(["name":"仪琳","id":"yi lin"]),
(["name":"哑妇","id":"yafu"]),
(["name":"定静师太","id":"dingjing shitai"]),
(["name":"仪和","id":"yi he"]),
(["name":"护靴使","id":"huxue shi"]),
(["name":"定逸师太","id":"dingyi shitai"]),
(["name":"仪清","id":"yi qing"]),
(["name":"秦绢","id":"qin juan"]),
(["name":"郑萼","id":"zheng e"]),
(["name":"定闲师太","id":"dingxian shitai"]),
(["name":"踏青妇人","id":"woman"]),
(["name":"官兵","id":"guan bing"]),
(["name":"恶霸","id":"eba"]),
(["name":"彭长老","id":"peng zhanglao"]),
(["name":"王朝","id":"wang chao"]),
(["name":"马汉","id":"ma han"]),
(["name":"富家公子","id":"gong zi"]),
(["name":"乞丐","id":"qi gai"]),
(["name":"护寺僧人","id":"seng ren"]),
(["name":"掌澡僧人","id":"seng ren"]),
(["name":"孔大官人","id":"kong"]),
(["name":"刘大财主","id":"liu caizhu"]),
(["name":"烧火僧人","id":"seng ren"]),
(["name":"素斋师傅","id":"seng ren"]),
(["name":"鲁智深","id":"lu zhisheng"]),
(["name":"老僧人","id":"old seng"]),
(["name":"泼皮","id":"popi"]),
(["name":"混混张三","id":"zhang san"]),
(["name":"卖菜汉子","id":"man"]),
(["name":"烧香老太","id":"old woman"]),
(["name":"智法长老","id":"zhifa zhanglao"]),
(["name":"智清长老","id":"zhi qing"]),
(["name":"监寺僧人","id":"jiansi seng"]),
(["name":"食客","id":"shi ke"]),
(["name":"高衙内","id":"gao yanei"]),
(["name":"陆虞候","id":"lu yuhou"]),
(["name":"刘麻子","id":"liu mazi"]),
(["name":"山陕甘会长","id":"hui zhang"]),
(["name":"皮货商","id":"pihuo shang"]),
(["name":"青衣","id":"qing yi"]),
(["name":"小生","id":"xiao sheng"]),
(["name":"李四","id":"li si"]),
(["name":"清竹道长","id":"qing zhu"]),
(["name":"乐厚","id":"yao hou"]),
(["name":"狄修","id":"di xiu"]),
(["name":"陆柏","id":"lu bai"]),
(["name":"史登达","id":"shi dengda"]),
(["name":"汤英鹄","id":"tang yinghu"]),
(["name":"万大平","id":"wan daping"]),
(["name":"左冷禅","id":"zuo lengchan"]),
(["name":"护盔使","id":"hukui shi"]),
(["name":"钟镇","id":"zhong zhen"]),
(["name":"费彬","id":"fei bing"]),
(["name":"邓八年","id":"deng banian"]),
(["name":"丁勉","id":"ding mian"]),
(["name":"高克新","id":"gao kexin"]),
(["name":"李铁嘴","id":"fortune teller"]),
(["name":"高根明","id":"gao genming"]),
(["name":"劳德诺","id":"lao denuo"]),
(["name":"岳灵珊","id":"yue lingshan"]),
(["name":"施戴子","id":"shi daizi"]),
(["name":"华山矮老者","id":"ai laozhe"]),
(["name":"华山高老者","id":"gao laozhe"]),
(["name":"护甲使","id":"hujia shi"]),
(["name":"岳不群","id":"yue buqun"]),
(["name":"陆大有","id":"lu dayou"]),
(["name":"宁中则","id":"ning zhongze"]),
(["name":"林平之","id":"lin pingzhi"]),
(["name":"令狐冲","id":"ling huchong"]),
(["name":"梁发","id":"liang fa"]),
(["name":"姚德忠","id":"yao dezhong"]),
(["name":"矛盾天师","id":"maodun tianshi"]),
(["name":"大堂经理","id":"datang jingli"]),
(["name":"徐霞客","id":"xu xiake"]),
(["name":"贾三","id":"jiasan"]),
(["name":"野羊寨寨丁","id":"zaiding"]),
(["name":"野羊寨小头目","id":"xiao toumu"]),
(["name":"野羊寨大头目","id":"da toumu"]),
(["name":"姚伯义","id":"yao boyi"]),
(["name":"欧阳野","id":"ouyang ye"]),
(["name":"土匪","id":"tu fei"]),
(["name":"咕噜拉玛","id":"gulu lama"]),
(["name":"小和尚","id":"xiao heshang"]),
(["name":"小沙弥","id":"xiao shami"]),
(["name":"信女","id":"xin nu"]),
(["name":"信男","id":"xin nan"]),
(["name":"护塔武僧","id":"wuseng"]),
(["name":"兵勇","id":"bingyong"]),
(["name":"老方丈","id":"lao fangzhang"]),
(["name":"街霸","id":"jieba"]),
(["name":"沈老财","id":"shen laocai"]),
(["name":"长工","id":"chang gong"]),
(["name":"黄世仁","id":"huang shiren"]),
(["name":"叶老板","id":"ye laoban"]),
(["name":"薛慕华","id":"xue muhua"]),
(["name":"李师师","id":"li shishi"]),
(["name":"萧狐齐","id":"xiao huqi"]),
(["name":"跑堂","id":"pao tang"]),
(["name":"巡捕","id":"xun bu"]),
(["name":"包不同","id":"bao butong"]),
(["name":"大弟子","id":"da dizi"]),
(["name":"弟子","id":"dizi"]),
(["name":"大师傅","id":"da shifu"]),
(["name":"张管家","id":"zhang guanjia"]),
(["name":"包不靓","id":"bao buliang"]),
(["name":"小童","id":"xiao tong"]),
(["name":"澡堂老板","id":"zaotang laoban"]),
(["name":"衙役","id":"ya yi"]),
(["name":"壮汉","id":"zhuang han"]),
(["name":"花匠","id":"hua jiang"]),
(["name":"围大人","id":"wei daren"]),
(["name":"顽童","id":"wan tong"]),
(["name":"男游客","id":"nan youke"]),
(["name":"女游客","id":"nu youke"]),
(["name":"崔百泉","id":"cui baiquan"]),
(["name":"阿碧","id":"a bi"]),
(["name":"护院","id":"huyuan"]),
(["name":"老夫人","id":"lao furen"]),
(["name":"阿朱","id":"a zhu"]),
(["name":"庄丁","id":"zhuang ding"]),
(["name":"邓百川","id":"deng baichuan"]),
(["name":"公冶乾","id":"gongye qian"]),
(["name":"慕容复","id":"murong fu"]),
(["name":"风波恶","id":"feng boe"]),
(["name":"姚伯当","id":"yao bodang"]),
(["name":"寨丁","id":"zai ding"]),
(["name":"诸保昆","id":"zhu baokun"]),
(["name":"司马林","id":"sima lin"]),
(["name":"老顾头","id":"lao gutou"]),
(["name":"幽草","id":"you cao"]),
(["name":"王语嫣","id":"wang yuyan"]),
(["name":"唐光雄","id":"tang guangxong"]),
(["name":"王夫人","id":"wang furen"]),
(["name":"严妈妈","id":"yan mama"]),
(["name":"老秀才","id":"lao xiucai"]),
(["name":"姚德彪","id":"yao debiao"]),
(["name":"洋保镖","id":"baobiao"]),
(["name":"马可皮罗","id":"makepilo"]),
(["name":"护塔僧","id":"seng"]),
(["name":"方哲朴","id":"fang zhepu"]),
(["name":"恶奴","id":"enu"]),
(["name":"骑士","id":"qi shi"]),
(["name":"守备","id":"shoubei"]),
(["name":"陈老曲","id":"chen laoqu"]),
(["name":"武馆弟子","id":"wuguan dizi"]),
(["name":"胖厨师","id":"chushi"]),
(["name":"石龙","id":"shilong"]),
(["name":"霍小玉","id":"huo xiaoyu"]),
(["name":"洪七公","id":"hong qigong"]),
(["name":"马媒婆","id":"meipo"]),
(["name":"道济和尚","id":"daoji"]),
(["name":"法海和尚","id":"fahai"]),
(["name":"东坡居士","id":"dongpo"]),
(["name":"白素贞","id":"bai suzhen"]),
(["name":"许仙","id":"xuxian"]),
(["name":"村姑","id":"cun gu"]),
(["name":"行人","id":"xingren"]),
(["name":"庄丁","id":"zhuangding"]),
(["name":"奴仆","id":"nupu"]),
(["name":"丁坚","id":"dingjian"]),
(["name":"施令威","id":"shilingwei"]),
(["name":"四庄主传功弟子","id":"dizi"]),
(["name":"丹青生","id":"danqing sheng"]),
(["name":"三庄主传功弟子","id":"dizi"]),
(["name":"秃笔翁","id":"tubi weng"]),
(["name":"黑白子","id":"heibai zi"]),
(["name":"二庄主传功弟子","id":"dizi"]),
(["name":"大庄主传功弟子","id":"dizi"]),
(["name":"黄钟公","id":"huangzhong gong"]),
(["name":"谢璎","id":"xie ying"]),
(["name":"陈老板","id":"chen laoban"]),
(["name":"孙二娘","id":"sun erniang"]),
(["name":"翠儿","id":"cui er"]),
(["name":"田老爹","id":"laodie"]),
(["name":"趟子手","id":"tangzi shou"]),
(["name":"镖头","id":"biao tou"]),
(["name":"猎人","id":"lie ren"]),
(["name":"清济","id":"qing ji"]),
(["name":"华严","id":"hua yan"]),
(["name":"净济","id":"jing ji"]),
(["name":"澄观","id":"cheng guan"]),
(["name":"晦明","id":"hui ming"]),
(["name":"观证","id":"guan zheng"]),
(["name":"觉非","id":"jue fei"]),
(["name":"大悲","id":"da bei"]),
(["name":"白衣人","id":"baiyi ren"]),
(["name":"蓝衣少年","id":"shaonian"]),
(["name":"尚天一","id":"shang tianyi"]),
(["name":"老王头","id":"lao wang"]),
(["name":"谢琳","id":"xie lin"]),
(["name":"山庄弟子","id":"dizi"]),
(["name":"落雁老人","id":"luoyan master"]),
(["name":"郭啸天","id":"guo xiaotian"]),
(["name":"花无邪","id":"hua wuxie"]),
(["name":"棠儿","id":"tanger"]),
(["name":"蕙儿","id":"huier"]),
(["name":"兰儿","id":"laner"]),
(["name":"碧涟","id":"bilian"]),
(["name":"朱由穆","id":"zhu youmu"]),
(["name":"铁桥三","id":"tie qiaosan"]),
(["name":"猿长老","id":"zhanglao"]),
(["name":"熊猫儿","id":"xiongmao er"]),
(["name":"温方海","id":"wen fanghai"]),
(["name":"吴四郎","id":"wu silang"]),
(["name":"叶天士","id":"ye tianshi"]),
(["name":"人贩子","id":"ren fanzi"]),
(["name":"小孩子","id":"xiaohai"]),
(["name":"独行盗","id":"duxing dao"]),
(["name":"说书老人","id":"oldman"]),
(["name":"周小妹","id":"zhou xiaomei"]),
(["name":"青衣妇人","id":"woman"]),
(["name":"端木良庸","id":"duanmu liangyong"]),
(["name":"宋缺","id":"songque"]),
(["name":"制胎工匠","id":"gongjiang"]),
(["name":"烧窑工","id":"gongren"]),
(["name":"伐木工","id":"famu gong"]),
(["name":"樵夫","id":"qiao fu"]),
(["name":"穷汉","id":"poor man"]),
(["name":"侯员外","id":"hou yuanwai"]),
(["name":"地保","id":"dibao"]),
(["name":"尹志平","id":"yin zhiping"]),
(["name":"赵志敬","id":"zhao zhijing"]),
(["name":"知客道长","id":"zhike daozhang"]),
(["name":"道童","id":"tong"]),
(["name":"谭处端","id":"tan chuduan"]),
(["name":"掌药道长","id":"zhangyao"]),
(["name":"王处一","id":"wang chuyi"]),
(["name":"郝大通","id":"hao datong"]),
(["name":"掌理道长","id":"zhangli"]),
(["name":"李志常","id":"li zhichang"]),
(["name":"马钰","id":"ma yu"]),
(["name":"掌经道长","id":"zhangjing"]),
(["name":"孙不二","id":"sun buer"]),
(["name":"丘处机","id":"qiu chuji"]),
(["name":"祁志诚","id":"qi zhicheng"]),
(["name":"火工道人","id":"huogong"]),
(["name":"跛足道人","id":"daoren"]),
(["name":"云游僧","id":"seng"]),
(["name":"清源居士","id":"jushi"]),
(["name":"阿芙","id":"a fu"]),
(["name":"鲁有脚","id":"lu youjiao"]),
(["name":"郑和","id":"zheng he"]),
(["name":"杂耍艺人","id":"yiren"]),
(["name":"云游道人","id":"daoren"]),
(["name":"姚德义","id":"yao deyi"]),
(["name":"孙朝奉","id":"sun chaofeng"]),
(["name":"护法僧","id":"seng"]),
(["name":"念真和尚","id":"nian zhen"]),
(["name":"胖和尚","id":"heshang"]),
(["name":"渔民","id":"fisherman"]),
(["name":"渔妇","id":"fisher"]),
(["name":"敲钟老人","id":"oldman"]),
(["name":"牧童","id":"mutong"]),
(["name":"伊斯兰教徒","id":"jiaotu"]),
(["name":"阿普都拉","id":"apu dula"]),
(["name":"孙都察","id":"sun"]),
(["name":"捡贝壳的小女孩","id":"girl"]),
(["name":"老渔翁","id":"yu weng"]),
(["name":"渔夫","id":"fisherman"]),
(["name":"刘三爷","id":"liusan"]),
(["name":"梁师爷","id":"liang shiye"]),
(["name":"佃户","id":"dianhu"]),
(["name":"张财主","id":"caizhu"]),
(["name":"长须老者","id":"oldman"]),
(["name":"宗王师","id":"zong wangshi"]),
(["name":"宗无畏","id":"zong wuwei"]),
(["name":"护法","id":"hufa"]),
(["name":"洞冥子","id":"dongming zi"]),
(["name":"张三","id":"zhang san"]),
(["name":"知客道长","id":"zhike daozhang"]),
(["name":"莫声谷","id":"mo shenggu"]),
(["name":"宋远桥","id":"song yuanqiao"]),
(["name":"谷虚道长","id":"guxu daozhang"]),
(["name":"俞莲舟","id":"yu lianzhou"]),
(["name":"守园道长","id":"shouyuan daozhang"]),
(["name":"张翠山","id":"zhang cuishan"]),
(["name":"殷梨亭","id":"yin litin"]),
(["name":"张松溪","id":"zhang songxi"]),
(["name":"清虚道长","id":"qingxu daozhang"]),
(["name":"张三丰","id":"zhang sanfeng"]),
(["name":"土匪头","id":"tufei tou"]),
(["name":"周富康","id":"zhou fukang"]),
(["name":"圆觉禅师","id":"yuan chanshi"]),
(["name":"张禽林","id":"zhang qinlin"]),
(["name":"王二娘","id":"wang erniang"]),
(["name":"约翰斯","id":"yuehan si"]),
(["name":"秋娃","id":"qiu wa"]),
(["name":"陆羽","id":"lu yu"]),
(["name":"刘一小","id":"liu yixiao"]),
(["name":"吴惊天","id":"wu jingtian"]),
(["name":"温方义","id":"wen fangyi"]),
(["name":"陆大娘","id":"lu daniang"]),
(["name":"沈金音","id":"shen jinyin"]),
(["name":"王诚","id":"wang cheng"]),
(["name":"壮汉","id":"man"]),
(["name":"老烂眼","id":"lao lanyan"]),
(["name":"小烂眼","id":"xiao lanyan"]),
(["name":"谢云烟","id":"xie yunyan"]),
(["name":"谢长风","id":"xie changfeng"]),
(["name":"扫墓人","id":"sao muren"]),
(["name":"陈麻婆","id":"chen mapo"]),
(["name":"张木匠","id":"zhang mujiang"]),
(["name":"王永康","id":"wang yongkang"]),
(["name":"李得发","id":"li defa"]),
(["name":"药铺伙计","id":"yaopu huoji"]),
(["name":"杜甫","id":"du fu"]),
(["name":"学童","id":"xuetong"]),
(["name":"燕六","id":"yan liu"]),
(["name":"大汉","id":"da han"]),
(["name":"薛金英","id":"xue jinyin"]),
(["name":"符永祥","id":"fu"]),
(["name":"战其力","id":"zhan qili"]),
(["name":"孙慧珊","id":"sun huisan"]),
(["name":"唐柔","id":"tang rou"]),
(["name":"左丘超然","id":"zuo qiu"]),
(["name":"唐方","id":"tang fang"]),
(["name":"萧秋水","id":"xiao"]),
(["name":"邓玉函","id":"deng yuhan"]),
(["name":"左常生","id":"zuo changsheng"]),
(["name":"华孤坟","id":"hua guwen"]),
(["name":"丘伯","id":"qiu bo"]),
(["name":"辛虎丘","id":"xin huqiu"]),
(["name":"张妈","id":"zhang ma"]),
(["name":"张临意","id":"zhang"]),
(["name":"广伯","id":"guang bo"]),
(["name":"沙千灯","id":"sha qiandeng"]),
(["name":"朱侠武","id":"zhu xiawu"]),
(["name":"萧西楼","id":"xiao xilou"]),
(["name":"登雕梁","id":"deng diaoliang"]),
(["name":"温艳阳","id":"wen yanyang"]),
(["name":"江秀音","id":"jiang xiuyin"]),
(["name":"铁心月","id":"tie xinyue"]),
(["name":"邱南顾","id":"qiu nangu"]),
(["name":"钟无离","id":"zhong wuli"]),
(["name":"柳有孔","id":"liu youkong"]),
(["name":"孔扬秦","id":"kong yangqin"]),
(["name":"何昆","id":"hekun"]),
(["name":"秤千金","id":"chen"]),
(["name":"管八方","id":"guan"]),
(["name":"傅天义","id":"fu tianyi"]),
(["name":"黑老汉","id":"oldman"]),
(["name":"黑衣人","id":"heiyi ren"]),
(["name":"王诚","id":"wang cheng"]),
(["name":"桑三娘","id":"shang sanniang"]),
(["name":"童百熊","id":"tongbai xiong"]),
(["name":"紫衫侍者","id":"zishan shizhe"]),
(["name":"杨莲亭","id":"yang lianting"]),
(["name":"成德殿殿下弟子","id":"dizi"]),
(["name":"东方不败","id":"dongfang bubai"]),
(["name":"张乘风","id":"zhang chengfeng"]),
(["name":"张乘云","id":"zhang chengyun"]),
(["name":"赵鹤","id":"zhao he"]),
(["name":"范松","id":"fan song"]),
(["name":"黄伯流","id":"huang boliu"]),
(["name":"向问天","id":"xiang wentian"]),
(["name":"贾布","id":"jia bu"]),
(["name":"日月教教徒","id":"jiao tu"]),
(["name":"青龙堂弟子","id":"dizi"]),
(["name":"贝锦仪","id":"bei jinyi"]),
(["name":"静道师太","id":"jingdao shitai"]),
(["name":"静慧师太","id":"jinghui shitai"]),
(["name":"静风师太","id":"jingfeng shitai"]),
(["name":"方碧琳","id":"fang bilin"]),
(["name":"道明小和尚","id":"daoming"]),
(["name":"静闲师太","id":"jingxian shitai"]),
(["name":"静迦师太","id":"jingjia shitai"]),
(["name":"李明霞","id":"li mingxia"]),
(["name":"赵灵珠","id":"zhao lingzhu"]),
(["name":"文方小师太","id":"wenfang"]),
(["name":"静虚师太","id":"jingxu shitai"]),
(["name":"灭绝师太","id":"miejue shitai"]),
(["name":"文晖小师太","id":"wenhui"]),
(["name":"静空师太","id":"jingkong shitai"]),
(["name":"文清小师太","id":"wenqing"]),
(["name":"静玄师太","id":"jingxuan shitai"]),
(["name":"苏梦清","id":"su mengqing"]),
(["name":"周芷若","id":"zhou zhiruo"]),
(["name":"花花公子","id":"playboy"]),
(["name":"张铁蛋","id":"zhang tiedan"]),
(["name":"农民","id":"man"]),
(["name":"小山贼","id":"xiao shanzei"]),
(["name":"金花","id":"jin hua"]),
(["name":"山贼","id":"shan zei"]),
(["name":"山贼头","id":"sanzei tou"]),
(["name":"舞蛇人","id":"snaker"]),
(["name":"黄小九","id":"huang xiaojiu"]),
(["name":"农家妇女","id":"woman"]),
(["name":"王老五","id":"wang laowu"]),
(["name":"欧阳锋","id":"ouyang feng"]),
(["name":"李教头","id":"li"]),
(["name":"教练","id":"trainer"]),
(["name":"小青","id":"qing"]),
(["name":"黑多隆","id":"hei duolong"]),
(["name":"台夷商贩","id":"shang fan"]),
(["name":"台夷妇女","id":"fu nu"]),
(["name":"台夷猎人","id":"lie ren"]),
(["name":"士兵","id":"shi bing"]),
(["name":"阿美","id":"a mei"]),
(["name":"祭司","id":"ji si"]),
(["name":"台夷姑娘","id":"gu niang"]),
(["name":"阿珂玛","id":"a kema"]),
(["name":"台夷农妇","id":"nong fu"]),
(["name":"盛皮罗客商","id":"ke shang"]),
(["name":"武将","id":"wu jiang"]),
(["name":"马夫","id":"ma fu"]),
(["name":"黄衣卫士","id":"wei shi"]),
(["name":"大土司","id":"da tusi"]),
(["name":"侍从","id":"shi cong"]),
(["name":"大土司","id":"da tusi"]),
(["name":"族头人","id":"zu touren"]),
(["name":"南国姑娘","id":"girl"]),
(["name":"摆夷老叟","id":"oldman"]),
(["name":"钱阿牛","id":"qian aniu"]),
(["name":"摆夷小孩","id":"kid"]),
(["name":"梁长老","id":"liang zhanglao"]),
(["name":"何红药","id":"he hongyao"]),
(["name":"薛慕汉","id":"xue muhan"]),
(["name":"赵老杆","id":"zhao laogan"]),
(["name":"傅思归","id":"fu sigui"]),
(["name":"褚万里","id":"zhu wanli"]),
(["name":"锦衣卫士","id":"wei shi"]),
(["name":"黄衣卫士","id":"wei shi"]),
(["name":"段无畏","id":"duan wuwei"]),
(["name":"霍先生","id":"huo xiansheng"]),
(["name":"养花女","id":"yanghua nu"]),
(["name":"木婉清","id":"mu wanqing"]),
(["name":"段正淳","id":"duan zhengchun"]),
(["name":"古笃诚","id":"gu ducheng"]),
(["name":"朱丹臣","id":"zhu danchen"]),
(["name":"高升泰","id":"gao shengtai"]),
(["name":"内侍","id":"nei shi"]),
(["name":"宫女","id":"gong nu"]),
(["name":"灵琦儿","id":"ling qier"]),
(["name":"贵公子","id":"gongzi"]),
(["name":"老祭司","id":"lao jisi"]),
(["name":"本观","id":"ben guan"]),
(["name":"本相","id":"ben xiang"]),
(["name":"本尘","id":"ben chen"]),
(["name":"枯荣大师","id":"ku rong"]),
(["name":"本参","id":"ben can"]),
(["name":"扫地僧","id":"saodi seng"]),
(["name":"本因","id":"ben yin"]),
(["name":"素衣卫士","id":"wei shi"]),
(["name":"傣族首领","id":"daizu shouling"]),
(["name":"陪从","id":"pei cong"]),
(["name":"无量剑弟子","id":"wuliang dizi"]),
(["name":"神农帮弟子","id":"shennong dizi"]),
(["name":"破疑","id":"po yi"]),
(["name":"破嗔","id":"po chen"]),
(["name":"陈家洛","id":"chen jialuo"]),
(["name":"香香公主","id":"gong zhu"]),
(["name":"回族战士","id":"zhan shi"]),
(["name":"木卓伦","id":"mu zhuolun"]),
(["name":"霍青桐","id":"huo qingtong"]),
(["name":"霍阿伊","id":"huo ayi"]),
(["name":"回族少女","id":"shao nv"]),
(["name":"巫士","id":"wushi"]),
(["name":"刘嫂","id":"liu sao"]),
(["name":"余婆婆","id":"yu popo"]),
(["name":"梅剑","id":"mei jian"]),
(["name":"兰剑","id":"lan jian"]),
(["name":"虚竹","id":"xu zhu"]),
(["name":"冯婆婆","id":"feng popo"]),
(["name":"周婆婆","id":"zhou popo"]),
(["name":"符敏仪","id":"fu mingyi"]),
(["name":"裘婆婆","id":"qiu popo"]),
(["name":"冯婆婆","id":"feng popo"]),
(["name":"石嫂","id":"shi sao"]),
(["name":"天山童姥","id":"tong lao"]),
(["name":"白龟寿","id":"bai guishou"]),
(["name":"高山王","id":"gao shanwang"]),
(["name":"封弓影","id":"feng gongying"]),
(["name":"常金鹏","id":"chang jinpeng"]),
(["name":"明教大汉","id":"da han"]),
(["name":"程嘲风","id":"cheng chaofeng"]),
(["name":"拓跋","id":"tuoba"]),
(["name":"冷谦","id":"leng qian"]),
(["name":"韦一笑","id":"wei yixiao"]),
(["name":"严垣","id":"yan yuan"]),
(["name":"闻松","id":"wen song"]),
(["name":"彭莹玉","id":"peng yingyu"]),
(["name":"周颠","id":"zhou dian"]),
(["name":"庄铮","id":"zhuang zheng"]),
(["name":"说不得","id":"shuo bude"]),
(["name":"张中","id":"zhang zhong"]),
(["name":"唐洋","id":"tang yang"]),
(["name":"辛然","id":"xin ran"]),
(["name":"胡青牛","id":"hu qingniu"]),
(["name":"殷无福","id":"yin wufu"]),
(["name":"殷野王","id":"yin yewang"]),
(["name":"殷无寿","id":"yin wushou"]),
(["name":"李天垣","id":"li tianyuan"]),
(["name":"殷无禄","id":"yin wulu"]),
(["name":"杨逍","id":"yang xiao"]),
(["name":"范遥","id":"fan yao"]),
(["name":"谢逊","id":"xie xun"]),
(["name":"张无忌","id":"zhang wuji"]),
(["name":"殷天正","id":"yin tianzheng"]),
(["name":"黛绮丝","id":"dai qisi"]),
});
















