mapping *persons=({
           ([    "name":"强盗",
                 "id":"qiangdao",
                 "age":34,
                 "combat_exp":2000,
                 "skill":([
                     "unarmed":20,
                     "parry":20,
                     "dodge":20,
                     ]),
                  "cloth":"/obj/cloth",
                  "weapon":"/obj/weapon/blade",
             ]),
            ([     "name":"窃贼",
                   "id":"qie zei",
                   "age":23,
                   "combat_exp":500,
                   "skill":([
               "unarmed":10,
               "parry":10,
               "dodge":10,  ]),
               "cloth":"/obj/cloth",
              ]),
            ([     "name":"山贼",
                   "id":"san zei",
                   "age":45,
                   "combat_exp":6000,
                   "skill":([
                "parry":40,
                "unarmed":40,
                "dodge":40,
                "blade":40,   ]),
              "cloth":"/obj/cloth",
              "weapon":"/obj/weapon/banfu",
              ]),
            ([   "name":"水盗",
                 "id":"shui dao",
                 "age":56,
                 "combat_exp":7000,
                 "skill":([
               "parry":50,
               "blade":50,
               "unarmed":50,
               "dodge":50,  ]),
              "weapon":"/obj/weapon/blade",
               ]),
             ([    "name":"绿林好汉",
                   "id":"haohan",
                   "age":34,
                   "combat_exp":5000,
                   "skill":([
                 "parry":35,
                 "unarmed":35,
                 "dodge":35,
                 "whip":35,]),
		"weapon":"/obj/std/weapon/pibian",
              ]),
             ([      "name":"小喽罗",
                     "id":"xiao louluo",
                     "age":23,
                     "combat_exp":900,
                     "skill":([
                  "parry":20,
                  "unarmed":20,
                  "dodge":20,
                  "blade":20,]),
               "cloth":"/obj/cloth",
               "weapon":"/obj/std/weapon/gangdao",
               ]),
             ([       "name":"云游僧人",
                      "id":"yunyou seng",
                      "combat_exp":12000,
                      "age":56,
                      "skill":([
                   "parry":60,
                   "unarmed":60,
                   "dodge":60,]),
                "cloth":"/obj/armor/seng-cloth",
               ]),
             ([       "name":"化缘僧",
                      "id":"huayuan seng",
                      "combat_exp":4000,
                      "age":30,
                      "skill":([
                   "parry":20,
                   "dodge":20,
                   "unarmed":20,]),
                 "cloth":"/obj/armor/seng-cloth",
                 ]),
             ([       "name":"风水术士",
                      "id":"fengshui shi",
                      "combat_exp":20000,
                      "age":67,
                      "skill":([
                   "parry":60,
                   "unarmed":60,
                   "dodge":60,]),
                 "cloth":"/obj/armor/dao-cloth",
                 ]),
              ([       "name":"行脚道人",
                       "id":"daoren",
                       "combat_exp":5000,
                       "age":32,
                       "skill":([
                    "parry":43,
                    "unarmed":43,
                    "dodge":43,]),
                 "cloth":"/obj/armor/dao-cloth",
                 ]),
               ([       "name":"小道士",
                        "age":15,
                        "combat_exp":200,
                        "id":"xiao daoshi",
                    "cloth":"/obj/armor/dao-cloth",
                 ]),
               ([       "name":"老家人",
                        "id":"lao jiaren",
                        "age":76,
                        "combat_exp":400,
                    "cloth":"/obj/cloth",
                 ]),
               ([      "name":"卖唱女孩",
                       "id":"girl",
                       "gender":"女性",
                       "age":17,
                       "combat_exp":600,
                    "cloth":"/obj/armor/female4-cloth",
                    ]),
               ([       "name":"瞎子",
                        "id":"xia zi",
                        "age":45,
                        "combat_exp":7000,
                    "cloth":"/obj/cloth",
                    ]),
               ([       "name":"财主",
                        "id":"cai zhu",
                        "age":56,
                        "combat_exp":7000,
                    ]),
                ([      "name":"流浪儿",
                        "id":"liulang er",
                        "combat_exp":100,
                        "age":14,
                    ]),
               ([       "name":"小丫鬟",
                        "id":"xiao yahuan",
                        "combat_exp":300,
                        "gender":"女性",
                        "age":15,
                        "cloth":"/obj/armor/female5-cloth",
                    ]),
                ([       "name":"地痞",
                         "id":"di pi",
                         "combat_exp":2500,
                         "age":23,
                    ]),
                ([       "name":"道姑",
                         "age":23,
                         "gender":"女性",
                         "id":"dao gu",
                         "combat_exp":12000,
                     ]),
               ([       "name":"老郎中",
                        "age":56,
                        "id":"lao langzhong",           
                        "combat_exp":7000,
                     ]),
            });
