inherit NPC;
void create()
{
     set_name("长须老者",({"oldman","laozhe","laoren"}));
     set("gender","男性");
     set("age",76);
     set("combat_exp",2000000);
     set("max_force",2000);
     set("force",2000);
     set("force_factor",200);
     set("chat_chance",20);
     set("chat_msg",({
         "前面树林里的屋子,你们可千万不要去,那里闹鬼!\n",
         "每当月圆之夜,就能听到庄家老屋女人和小孩的哭声!\n",
         "那片黑森林十分古怪,不知道的人一定摸不到路!\n",
         }));
      set("inquiry",([
               "庄家老屋":"进了树林,北,东,西,北,就行了!\n",
               "黑森林":"进了树林,北,东,西,北,就行了!\n",
               ]));
      set_skill("unarmed",200);
      set_skill("parry",200);
      set_skill("dodge",200);
      set_skill("force",200);
      set_skill("literate",200);
      setup();
      carry_object("/obj/cloth")->wear();
      add_money("gold",5);
}